/**
 * Arabic diacritics were generated by https://github.com/CAMeL-Lab/camel_tools
 */

import assert from "assert";
import { readFileSync } from "fs";
import { join } from "path";

const original = readFileSync(join("arabic.txt"), "utf8").trim().split("\n");
const diacritics = readFileSync(join("arabic-diacritics.txt"), "utf8")
  .trim()
  .split("\n");
assert(original.length === diacritics.length);

export const originalToDiacritics = Object.fromEntries(
  original.map((text, i) => [text, diacritics[i]])
);
